name: energydata-env
dependencies:
- openssl=1.0.2h=1
- pip=8.1.2=py27_0
- python=2.7.12=0
- readline=6.2=2
- setuptools=23.0.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pip:
  - cycler==0.10.0
  - decorator==4.0.9
  - matplotlib==1.5.1
  - networkx==1.11
  - numpy==1.11.0
  - pandas==0.18.1
  - pillow==3.2.0
  - plotly==1.9.9
  - pyparsing==2.1.1
  - python-dateutil==2.5.2
  - pytz==2016.3
  - requests==2.9.1
  - scikit-learn==0.17.1
  - scipy==0.17.0
  - seaborn==0.7.1
  - six==1.10.0

